### ISSUE TITLE
Installing Plugin as Part of Dockerfile

### ISSUE THREAD

**Issue by jorymorrison** [bitnami/bitnami-docker-discourse#111]
**Description**

I'm attempting to provide a plugin (LDAP Plugin) at container launch.

**Approach so far:**

Making the following modifications to the Dockerfile:

```
RUN mkdir -p /bitnami/discourse/plugins/discourse-ldap-auth
COPY discourse-ldap-auth/* /bitnami/discourse/plugins/discourse-ldap-auth/
RUN chown -R root:root /bitnami/discourse/plugins/discourse-ldap-auth/
RUN chmod -R 777 /bitnami/discourse/plugins/discourse-ldap-auth/
```

**Describe the results you received:**

Result in the following error during launch. Discourse and sidekiq do not come up.

```
[ec2-user@discourse-server ~]$ docker logs discourse_discourse_1

Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
postgre ERROR [canConnect] Connection with 'bn_discourse' user is unsuccessful
postgre INFO  ==> Creating database bitnami_application...
postgre INFO  ==> Granting access to bn_discourse to the database bitnami_application...
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Configuring Discourse database...
discour INFO  Enabling PostgreSQL plugins for Discourse...
discour INFO  Migrating database...
discour INFO  Creating the Discourse admin user...
discour INFO  Configuring your Discourse installation...
Error executing 'postInstallation': rake aborted!
LoadError: cannot load such file -- /opt/bitnami/discourse/plugins/discourse-ldap-auth/lib/ldap_user
/opt/bitnami/discourse/plugins/discourse-ldap-auth/plugin.rb:14:in `require_relative'
/opt/bitnami/discourse/plugins/discourse-ldap-auth/plugin.rb:14:in `activate!'
/opt/bitnami/discourse/lib/plugin/instance.rb:486:in `instance_eval'
/opt/bitnami/discourse/lib/plugin/instance.rb:486:in `activate!'
lib/discourse.rb:171:in `block in activate_plugins!'
lib/discourse.rb:168:in `each'
lib/discourse.rb:168:in `activate_plugins!'
/opt/bitnami/discourse/config/application.rb:261:in `<class:Application>'
/opt/bitnami/discourse/config/application.rb:58:in `<module:Discourse>'
/opt/bitnami/discourse/config/application.rb:57:in `<top (required)>'
/opt/bitnami/discourse/Rakefile:7:in `require'
/opt/bitnami/discourse/Rakefile:7:in `<top (required)>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

Which tells me that perhaps the entrypoint -> init.sh -> nami_initialize sequence is not performing the rake required to install the plugin. How is installation of plugins officially supported? 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
[ec2-user@discourse-server ~]$ docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.12.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.51GiB
 Name: REDACTED
 ID: IF3J:QUPH:RLCK:5OGT:HNGY:7EGL:PDDC:I4PA:MPXD:YR3H:D63I:2FTM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896
```

**Comment by miguelaeh** [comment]
Hi @jorymorrison ,
It seems to be a problem with the plugin, have you tried to use other plugin to see if it loaded correctly?
I guess rake is being executed as the trace giving the error is from the rake command

**Comment by jorymorrison** [comment]
I repulled the LDAP plugin and still didn't work. At your suggestion I also tried another plugin, which resulted in another rake error.

```
nami    TRACE Error: Error executing 'postInstallation': rake aborted!
LoadError: cannot load such file -- /opt/bitnami/discourse/plugins/discourse-chat-integration/lib/discourse_chat/provider/slack/slack_enabled_setting_validator
/opt/bitnami/discourse/plugins/discourse-chat-integration/plugin.rb:16:in `require_relative'
/opt/bitnami/discourse/plugins/discourse-chat-integration/plugin.rb:16:in `activate!'
/opt/bitnami/discourse/lib/plugin/instance.rb:486:in `instance_eval'
/opt/bitnami/discourse/lib/plugin/instance.rb:486:in `activate!'
lib/discourse.rb:171:in `block in activate_plugins!'
lib/discourse.rb:168:in `each'
lib/discourse.rb:168:in `activate_plugins!'
/opt/bitnami/discourse/config/application.rb:261:in `<class:Application>'
/opt/bitnami/discourse/config/application.rb:58:in `<module:Discourse>'
/opt/bitnami/discourse/config/application.rb:57:in `<top (required)>'
/opt/bitnami/discourse/Rakefile:7:in `require'
/opt/bitnami/discourse/Rakefile:7:in `<top (required)>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

    at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
    at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
    at Object.$app.helpers.execute (/root/.nami/components/com.bitnami.ruby/helpers.js:44:7)
    at Object.$app.helpers.bundleExecute (/root/.nami/components/com.bitnami.ruby/helpers.js:62:8)
    at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
    at Service.$app.postInstallation (/root/.nami/components/com.bitnami.discourse/main.js:75:8)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
[ec2-user@discourse-server discourse]$ 
```

**Comment by miguelaeh** [comment]
Hi @jorymorrison ,
I think it is a problem with the plugins itself, to mount a plugin you can add the following line to the `rootfs/init.sh` file:
```   17     fi
+  18     cd /bitnami/discourse/plugins && git clone https://github.com/discourse/discourse-spoiler-alert
   19     echo "Starting $4..."
``` 
That plugin (that is an official plugin) works, your plugin gives an error, so probably is an error with the plugin.

**Comment by miguelaeh** [comment]
Hi @jorymorrison 
I hope you will get a solution for that plugin, let us know if you have any issue with the image.
