### ISSUE TITLE
Latest release, 2.4.1, breaks update due to dependencies

### ISSUE THREAD

**Issue by freemo** [bitnami/bitnami-docker-discourse#135]
We have been running the Bitnami dockerized Discourse container for some time now, upgrades usually go smoothly. However on the most recent update to 2.4.1 released 18 hours ago our update now fails. When database migration initiates the following error is produced and the container exits:

```
Gem::LoadError: can't activate public_suffix-3.0.3, already activated public_suffix-4.0.3
```

Here is the full log with the above error in context:

```
2020-03-10T14:18:26.395382414Z Welcome to the Bitnami discourse container
2020-03-10T14:18:26.396716911Z Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
2020-03-10T14:18:26.396871853Z Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
2020-03-10T14:18:26.396944645Z Send us your feedback at containers@bitnami.com
2020-03-10T14:18:26.397030695Z 
2020-03-10T14:18:29.560967606Z nami    INFO  Initializing postgresql-client
2020-03-10T14:18:29.601153759Z nami    INFO  postgresql-client successfully initialized
2020-03-10T14:18:33.851068932Z nami    INFO  Initializing discourse
2020-03-10T14:18:33.918898995Z discour INFO  Patching Discourse...
2020-03-10T14:18:34.031575743Z postgre INFO  Trying to connect to PostgreSQL server
2020-03-10T14:18:34.054517462Z postgre INFO  Found PostgreSQL server listening at default-postgres.cjvkhc5ajvev.us-east-1.rds.amazonaws.com:5432
2020-03-10T14:18:34.148840672Z postgre INFO  PostgreSQL server listening and working at default-postgres.cjvkhc5ajvev.us-east-1.rds.amazonaws.com:5432
2020-03-10T14:18:34.148989484Z discour INFO  Preparing Discourse environment...
2020-03-10T14:18:34.151090891Z discour INFO  Configuring the Discourse database files...
2020-03-10T14:18:34.160605225Z discour INFO  Configuring Redis...
2020-03-10T14:18:34.165271005Z discour INFO  Setting up SMTP in Discourse...
2020-03-10T14:18:34.362602937Z discour INFO  Migrating database...
2020-03-10T14:18:55.636283428Z Error executing 'postInstallation': rake aborted!
2020-03-10T14:18:55.636318859Z Gem::LoadError: can't activate public_suffix-3.0.3, already activated public_suffix-4.0.3
2020-03-10T14:18:55.636325079Z /opt/bitnami/discourse/lib/plugin_gem.rb:20:in `load'
2020-03-10T14:18:55.636329209Z /opt/bitnami/discourse/lib/plugin/instance.rb:600:in `gem'
2020-03-10T14:18:55.636333049Z /opt/bitnami/discourse/plugins/discourse-github/plugin.rb:9:in `activate!'
2020-03-10T14:18:55.636336740Z /opt/bitnami/discourse/lib/plugin/instance.rb:508:in `instance_eval'
2020-03-10T14:18:55.636340639Z /opt/bitnami/discourse/lib/plugin/instance.rb:508:in `activate!'
2020-03-10T14:18:55.636344369Z lib/discourse.rb:191:in `block in activate_plugins!'
2020-03-10T14:18:55.636358519Z lib/discourse.rb:188:in `each'
2020-03-10T14:18:55.636364569Z lib/discourse.rb:188:in `activate_plugins!'
2020-03-10T14:18:55.636368629Z /opt/bitnami/discourse/config/application.rb:272:in `block in <class:Application>'
2020-03-10T14:18:55.636373440Z /opt/bitnami/discourse/lib/plugin_initialization_guard.rb:5:in `plugin_initialization_guard'
2020-03-10T14:18:55.636377030Z /opt/bitnami/discourse/config/application.rb:271:in `<class:Application>'
2020-03-10T14:18:55.636391579Z /opt/bitnami/discourse/config/application.rb:59:in `<module:Discourse>'
2020-03-10T14:18:55.636396290Z /opt/bitnami/discourse/config/application.rb:58:in `<top (required)>'
2020-03-10T14:18:55.636400140Z /opt/bitnami/discourse/Rakefile:7:in `require'
2020-03-10T14:18:55.636403690Z /opt/bitnami/discourse/Rakefile:7:in `<top (required)>'
2020-03-10T14:18:55.636407420Z /opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
2020-03-10T14:18:55.636411290Z /opt/bitnami/ruby/bin/bundle:23:in `load'
2020-03-10T14:18:55.636414740Z /opt/bitnami/ruby/bin/bundle:23:in `<main>'
2020-03-10T14:18:55.636418370Z (See full trace by running task with --trace)
```

**Comment by freemo** [comment]
Nevermind, the problem was an outdated plugin.
