### ISSUE TITLE
Production ready docker-compose

### ISSUE THREAD

**Issue by LM1LC3N7** [bitnami/bitnami-docker-discourse#194]
Hello,

This question may be related to this issue https://github.com/bitnami/bitnami-docker-discourse/issues/193.

I cannot understand how to create a `docker-compose.yml` file with a fully configured postgresql database and ask the discourse container to connect to it.
Each time, discourse fail to connect or initialize the DB.

To reproduce :
* Use your dedicated postgresql documentation here https://github.com/bitnami/bitnami-docker-discourse and create a postgresql container with the root user password
* Try to set discourse env variables to use this postgresql container, with NO empty passwords.

```bash
    postgresql:
      container_name: discourse_pgsql_test
      image: docker.io/bitnami/postgresql:11
      restart: unless-stopped
      environment:
        - ALLOW_EMPTY_PASSWORD=no
        - POSTGRESQL_PASSWORD=postgresqlUserPasswordtochange
        - POSTGRESQL_DATABASE=bitnami_discourse
      volumes:
        - postgresql_data_test:/bitnami/postgresql


 discourse:
    container_name: discourse_test
    image: docker.io/bitnami/discourse:2
    depends_on:
      - postgresql
      - redis
    volumes:
      - discourse_data_test:/bitnami/discourse
    environment:
      - BITNAMI_DEBUG=true
      # FIRST RUN
      - POSTGRESQL_CLIENT_POSTGRES_USER=bn_discourse
      - POSTGRESQL_CLIENT_POSTGRES_PASSWORD=anotherPasswordToChange
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - ALLOW_EMPTY_PASSWORD=no
      # POSTGRESQL
      - DISCOURSE_DATABASE_NAME=bitnami_discourse  # DB name
      - DISCOURSE_DATABASE_USER=postgres  # DB user name (root)
      - DISCOURSE_DATABASE_PASSWORD=postgresqlUserPasswordtochange # DB user password
      - DISCOURSE_DATABASE_HOST=postgresql # DB host
      # REDIS
      - DISCOURSE_REDIS_HOST=discourse_redis_test   # DB host
      - DISCOURSE_REDIS_PASSWORD=${DISCOURSE_REDIS_PASSWORD} # DB password
      # DISCOURSE CONFIG
      - DISCOURSE_USERNAME=${DISCOURSE_USERNAME}    # Default admin username
      - DISCOURSE_PASSWORD=${DISCOURSE_PASSWORD}    # Default admin password
      - DISCOURSE_EMAIL=${DISCOURSE_EMAIL}          # Default admin email
      - DISCOURSE_SITENAME="TEST - Résidence du Clos des Lièvres"
      - DISCOURSE_HOST=leclos-test.milcent.co            # Default site URL
      - DISCOURSE_ENABLE_HTTPS=yes                  # HTTPS by default
      - DISCOURSE_PORT_NUMBER=3000                  # Default running port
      - DISCOURSE_ENV=test                          # Allowed values are development, production, test
      - DISCOURSE_ENABLE_CONF_PERSISTENCE=yes       # Whether to enable persistence of the Discourse discourse.conf
      # SMTP CONFIG
      - DISCOURSE_SMTP_HOST=smtp.sparkpostmail.com
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=${DISCOURSE_SMTP_USER}
      - DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASS}
      - DISCOURSE_SMTP_TLS=yes
      - DISCOURSE_SMTP_AUTH=login
      # UNICORN CONFIG
      - UNICORN_WORKERS=4
```

Logs : 

```bash
discourse_pgsql_test | postgresql 16:15:18.07 INFO  ==> ** Starting PostgreSQL **
discourse_pgsql_test | 2021-06-14 16:15:18.088 GMT [1] LOG:  pgaudit extension initialized
discourse_pgsql_test | 2021-06-14 16:15:18.089 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
discourse_pgsql_test | 2021-06-14 16:15:18.089 GMT [1] LOG:  listening on IPv6 address "::", port 5432
discourse_pgsql_test | 2021-06-14 16:15:18.094 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
discourse_pgsql_test | 2021-06-14 16:15:18.110 GMT [86] LOG:  database system was interrupted; last known up at 2021-06-14 16:13:52 GMT
discourse_pgsql_test | 2021-06-14 16:15:18.236 GMT [86] LOG:  database system was not properly shut down; automatic recovery in progress
discourse_pgsql_test | 2021-06-14 16:15:18.239 GMT [86] LOG:  redo starts at 0/1658DD8
discourse_pgsql_test | 2021-06-14 16:15:18.239 GMT [86] LOG:  invalid record length at 0/1658E10: wanted 24, got 0
discourse_pgsql_test | 2021-06-14 16:15:18.239 GMT [86] LOG:  redo done at 0/1658DD8
discourse_pgsql_test | 2021-06-14 16:15:18.265 GMT [1] LOG:  database system is ready to accept connections
discourse_pgsql_test | 2021-06-14 16:15:18.416 GMT [93] FATAL:  password authentication failed for user "bn_discourse"
discourse_pgsql_test | 2021-06-14 16:15:18.416 GMT [93] DETAIL:  Role "bn_discourse" does not exist.
discourse_pgsql_test |  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
discourse_test | discourse 16:15:23.42 DEBUG ==> Executing SQL command:
discourse_test | SELECT 1
discourse_test | psql: error: FATAL:  password authentication failed for user "bn_discourse"
discourse_pgsql_test | 2021-06-14 16:15:23.437 GMT [95] FATAL:  password authentication failed for user "bn_discourse"
discourse_pgsql_test | 2021-06-14 16:15:23.437 GMT [95] DETAIL:  Role "bn_discourse" does not exist.
discourse_pgsql_test |  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
discourse_sidekiq_test | discourse 16:15:24.12 DEBUG ==> Executing SQL command:
discourse_sidekiq_test | SELECT 1
discourse_pgsql_test | 2021-06-14 16:15:24.136 GMT [96] FATAL:  password authentication failed for user "bn_discourse"
discourse_pgsql_test | 2021-06-14 16:15:24.136 GMT [96] DETAIL:  Role "bn_discourse" does not exist.
discourse_pgsql_test |  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
discourse_sidekiq_test | psql: error: FATAL:  password authentication failed for user "bn_discourse"
^CGracefully stopping... (press Ctrl+C again to force)
Stopping discourse_sidekiq_test ... done
Stopping discourse_test         ... done
Stopping discourse_redis_test   ... done
Stopping discourse_pgsql_test   ... done
```

**Comment by alemorcuq** [comment]
Hi, @LM1LC3N7.

This would be one way of doing it:

1. Create a PostgreSQL container with a password for the superuser (the superuser is `postgres` by default):

```
- POSTGRESQL_PASSWORD=mypassword
```

2. Create the Discourse container and instruct it to create the required database:

```
# This is the database and user Discord will use for the application. It does not exist yet, we are going to create it with other environment variables
- DISCOURSE_DATABASE_HOST=postgresql
- DISCOURSE_DATABASE_PORT_NUMBER=5432
- DISCOURSE_DATABASE_USER=bn_discourse
- DISCOURSE_DATABASE_PASSWORD=anotherpassword
- DISCOURSE_DATABASE_NAME=bitnami_discourse
# These are the credentials for the superuser so that the Discourse container can create a new user and database
- POSTGRESQL_CLIENT_POSTGRES_USER=postgres
- POSTGRESQL_CLIENT_POSTGRES_PASSWORD=mypassword
# This is the database and the user that it is going to create and use for the application
- POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
- POSTGRESQL_CLIENT_CREATE_DATABASE_USER=bn_discourse
- POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=anotherpassword
- POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
```

And that's it. Let me know if you have any questions.

**Comment by LM1LC3N7** [comment]
Hello,

Thank you very much it is very clear. But I have an error still, can you help?

```bash
discourse_test | discourse 13:43:48.98 INFO  ==> Populating database
discourse_test | rake aborted!
discourse_test | LoadError: cannot load such file -- rspec/core/rake_task
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
discourse_test | /opt/bitnami/discourse/lib/tasks/rspec.rake:4:in `<main>'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:326:in `block in load'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:326:in `load'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/engine.rb:675:in `block in run_tasks_blocks'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/engine.rb:675:in `each'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/engine.rb:675:in `run_tasks_blocks'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/application.rb:521:in `run_tasks_blocks'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/engine.rb:464:in `load_tasks'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/railtie.rb:207:in `public_send'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/railtie.rb:207:in `method_missing'
discourse_test | /opt/bitnami/discourse/Rakefile:9:in `<top (required)>'
discourse_test | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
discourse_test | /opt/bitnami/ruby/bin/bundle:23:in `load'
discourse_test | /opt/bitnami/ruby/bin/bundle:23:in `<main>'
discourse_test | (See full trace by running task with --trace)
discourse_test exited with code 1
```

**Comment by LM1LC3N7** [comment]
**Note** : The DB is new, all volumes are. So no old data that could create errors.

**Comment by alemorcuq** [comment]
I don't get that error on my end. Do you mind sharing your full `docker-compose.yml` so I can try to reproduce it?

**Comment by LM1LC3N7** [comment]
Sure.


```bash
version: '2'

services:

  postgresql:
    container_name: discourse_pgsql_test
    image: docker.io/bitnami/postgresql:11
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_PASSWORD=${DISCOURSE_PGSQL_PASS_ROOT}
    volumes:
      - postgresql_data_test:/bitnami/postgresql
    networks:
      - discourse_backend_test
    cpus: 1
    mem_limit: 512m
    memswap_limit: 512m


  redis:
    container_name: discourse_redis_test
    image: docker.io/bitnami/redis:6.0
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=${DISCOURSE_REDIS_PASSWORD}
    volumes:
      - redis_data_test:/bitnami/discourse
    networks:
      - discourse_backend_test
    #command: /opt/bitnami/scripts/redis/run.sh --maxmemory 1024mb
    cpus: 1
    mem_limit: 1024m
    memswap_limit: 1024m


  discourse:
    container_name: discourse_test
    image: docker.io/bitnami/discourse:2
    depends_on:
      - postgresql
      - redis
    volumes:
      - discourse_data_test:/bitnami/discourse
    environment:
      # DEBUG
      #- DISCOURSE_SKIP_BOOTSTRAP=yes                # For debugging plugins incompatibility
      - BITNAMI_DEBUG=true
      # This is the database and user Discord will use for the application.
      # It does not exist yet, we are going to create it with other environment variables
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=${DISCOURSE_PGSQL_USER}
      - DISCOURSE_DATABASE_PASSWORD=${DISCOURSE_PGSQL_PASS}
      - DISCOURSE_DATABASE_NAME=${DISCOURSE_PGSQL_DB}
      # These are the credentials for the superuser
      # so that the Discourse container can create a new user and database
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_POSTGRES_PASSWORD=${DISCOURSE_PGSQL_PASS_ROOT}
      # This is the database and the user that it is going to create and use for the application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=${DISCOURSE_PGSQL_DB}
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USER=${DISCOURSE_PGSQL_USER}
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=${DISCOURSE_PGSQL_PASS}
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - ALLOW_EMPTY_PASSWORD=no
      # REDIS
      - DISCOURSE_REDIS_HOST=discourse_redis_test   # DB host
      - DISCOURSE_REDIS_PASSWORD=${DISCOURSE_REDIS_PASSWORD} # DB password
      # DISCOURSE CONFIG
      - DISCOURSE_USERNAME=${DISCOURSE_USERNAME}    # Default admin username
      - DISCOURSE_PASSWORD=${DISCOURSE_PASSWORD}    # Default admin password
      - DISCOURSE_EMAIL=${DISCOURSE_EMAIL}          # Default admin email
      - DISCOURSE_SITENAME="TEST - Résidence du Clos des Lièvres"
      - DISCOURSE_HOST=sub.domain.tld            # Default site URL
      - DISCOURSE_ENABLE_HTTPS=yes                  # HTTPS by default
      - DISCOURSE_PORT_NUMBER=3000                  # Default running port
      - DISCOURSE_ENV=test                          # Allowed values are development, production, test
      - DISCOURSE_ENABLE_CONF_PERSISTENCE=yes       # Whether to enable persistence of the Discourse discourse.conf
      # SMTP CONFIG
      - DISCOURSE_SMTP_HOST=smtp.sparkpostmail.com
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=${DISCOURSE_SMTP_USER}
      - DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASS}
      - DISCOURSE_SMTP_TLS=yes
      - DISCOURSE_SMTP_AUTH=login
      # UNICORN CONFIG
      - UNICORN_WORKERS=4
    labels:
      # Base
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.discourse-test.entrypoints: "websecure"
      traefik.http.routers.discourse-test.middlewares: "security@file, compression@file"
      traefik.http.routers.discourse-test.tls: "true"
      traefik.http.routers.discourse-test.tls.certresolver: "cert"
      # Specific
      traefik.http.routers.discourse-test.rule: "Host(`sub.domain.tld`)"
    networks:
      - proxy
      - discourse_backend_test
    cpus: 4
    mem_limit: 3G
    memswap_limit: 3G


  sidekiq:
    container_name: discourse_sidekiq_test
    image: docker.io/bitnami/discourse:2
    depends_on:
      - discourse
    volumes:
      - discourse_sidekiq_test:/bitnami/discourse
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      - BITNAMI_DEBUG=true
      # POSTGRESQL
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=${DISCOURSE_PGSQL_USER}
      - DISCOURSE_DATABASE_PASSWORD=${DISCOURSE_PGSQL_PASS}
      - DISCOURSE_DATABASE_NAME=${DISCOURSE_PGSQL_DB}
      # REDIS
      - DISCOURSE_REDIS_HOST=discourse_redis_test   # DB host
      - DISCOURSE_REDIS_PASSWORD=${DISCOURSE_REDIS_PASSWORD} # DB password
      # DISCOURSE CONFIG
      - DISCOURSE_USERNAME=${DISCOURSE_USERNAME}    # Default admin username
      - DISCOURSE_PASSWORD=${DISCOURSE_PASSWORD}    # Default admin password
      - DISCOURSE_EMAIL=${DISCOURSE_EMAIL}          # Default admin email
      - DISCOURSE_SITENAME="TEST - Résidence du Clos des Lièvres"
      - DISCOURSE_HOST=sub.domain.tld            # Default site URL
      - DISCOURSE_ENABLE_HTTPS=yes                  # HTTPS by default
      - DISCOURSE_PORT_NUMBER=3000                  # Default running port
      - DISCOURSE_ENV=test                          # Allowed values are development, production, test
      - DISCOURSE_ENABLE_CONF_PERSISTENCE=yes       # Whether to enable persistence of the Discourse discourse.conf
      # SMTP CONFIG
      - DISCOURSE_SMTP_HOST=smtp.sparkpostmail.com
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=${DISCOURSE_SMTP_USER}
      - DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASS}
      - DISCOURSE_SMTP_TLS=yes
      - DISCOURSE_SMTP_AUTH=login
      # UNICORN CONFIG
      - UNICORN_WORKERS=4
    networks:
      - discourse_backend_test
    cpus: 4
    mem_limit: 1512m
    memswap_limit: 1512m



volumes:
  postgresql_data_test:
    name: discourse_pgsql_test_140621
    driver: local
  redis_data_test:
    name: discourse_redis_test_140621
    driver: local
  discourse_data_test:
    name: discourse_data_test_140621
    driver: local
  discourse_sidekiq_test:
    name: discourse_sidekiq_test_140621
    driver: local


networks:
  discourse_backend_test:
    name: discourse_backend_test
  proxy:
    name: proxy

```


Env file (fish format, you have to change it to use it for bash) : 

```bash
# POSTGRESQL DISCOURSE USER
set -Ux DISCOURSE_PGSQL_DB "bitnami_discourse"
set -Ux DISCOURSE_PGSQL_USER "bn_discourse"
set -Ux DISCOURSE_PGSQL_PASS "pgsqlPasswordToChange"
set -Ux DISCOURSE_PGSQL_PASS_ROOT "rootPgsqlPasswordToChange"

# REDIS PASSWORD
# /!\ DO NOT USE "@" in password
set -Ux DISCOURSE_REDIS_PASSWORD "redisPasswordToChange"

# DISCOURSE configuration
set -Ux DISCOURSE_USERNAME "username"
set -Ux DISCOURSE_PASSWORD "discoursePasswordToChange"
set -Ux DISCOURSE_EMAIL "email@email.tochange"

# SMTP config
set -Ux DISCOURSE_SMTP_USER "SMTP_Injection"
set -Ux DISCOURSE_SMTP_PASS "APIToChange"

```

**Comment by alemorcuq** [comment]
It looks like the issue comes from the `DISCOURSE_ENV=test` environment variable. Using the default `production` value it works.

I will create an internal task to analyze this.

**Comment by LM1LC3N7** [comment]
Thank you very much for your investigation, indeed it is working now, I am able to start investigating on #191 😄 
Also, thanks a lot for this new `docker-compose.yml`, I strongly suggest adding an example next to this file in the main repo.

**Comment by Mist-Hunter** [comment]
Just wanted to thank both of you for this exchange. I pretty much ran into the same issues when trying to move from the example config to production, found this thread, and then failed to change the test to production flag, search, found this thread again (reading comprehension failure :P) and am now up and running.
