### ISSUE TITLE
Container fails with no error message during DB migration and exits.

### ISSUE THREAD

**Issue by freemo** [bitnami/bitnami-docker-discourse#199]
I have had a stably running version of bitami's discourse container for some time. I went to upgrade it, it was running bitnami/discourse:2 so it is updating to the latest version of 2. However during the migration step it tries to process for some time and then exits with no error code causing the container to shutdown and restart repeatedly.

I tinkered with the code a bit and it appears this is happening whent he `rake db:migrate` command is called.

Here is the log output:

```
2021-07-25T15:11:15.142941750Z discourse 15:11:15.14 
2021-07-25T15:11:15.144514813Z discourse 15:11:15.14 Welcome to the Bitnami discourse container
2021-07-25T15:11:15.147413767Z discourse 15:11:15.14 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
2021-07-25T15:11:15.148723258Z discourse 15:11:15.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
2021-07-25T15:11:15.152726731Z discourse 15:11:15.14 
2021-07-25T15:11:15.174516992Z discourse 15:11:15.17 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
2021-07-25T15:11:15.176851752Z discourse 15:11:15.17 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
2021-07-25T15:11:15.191866077Z discourse 15:11:15.19 INFO  ==> Trying to connect to the database server
2021-07-25T15:11:15.263489744Z discourse 15:11:15.26 INFO  ==> Creating database user discourse
2021-07-25T15:11:15.318084868Z discourse 15:11:15.31 INFO  ==> Creating database discourse
2021-07-25T15:11:15.565225757Z discourse 15:11:15.56 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
2021-07-25T15:11:15.571894972Z discourse 15:11:15.57 INFO  ==> Creating Discourse configuration file
2021-07-25T15:11:15.618696892Z discourse 15:11:15.61 INFO  ==> Enabling SMTP
2021-07-25T15:11:15.673656030Z discourse 15:11:15.67 INFO  ==> Restoring persisted Discourse installation
2021-07-25T15:11:15.836349765Z discourse 15:11:15.83 INFO  ==> Trying to connect to the database server
2021-07-25T15:11:15.865762900Z discourse 15:11:15.86 INFO  ==> Running database migrations
```

**Version**

```
Client:
 Version:           20.10.7
 API version:       1.40
 Go version:        go1.16.4
 Git commit:        f0df35096d
 Built:             Fri Jun  4 08:14:39 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 18
  Running: 16
  Paused: 0
  Stopped: 2
 Images: 56
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: kajaboq13kghgnkrwdbodhher
  Is Manager: true
  ClusterID: khkgpurcjli0zuecvir60d0m8
  Managers: 6
  Nodes: 7
  Default Address Pool: 192.168.0.0/16  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 1
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.0.82
  Manager Addresses:
   10.0.0.118:2377
   10.0.0.82:2377
   10.0.1.186:2377
   10.0.2.162:2377
   10.0.3.112:2377
   10.0.5.16:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1028-aws
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 15.39GiB
 Name: swarm-hybrid-1
 ID: AUU5:ED67:NCAO:YXJC:HTAE:GEUE:E55Y:XPJD:WH2Q:KHD2:GBM7:IXSB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: freemo
 Registry: https://index.docker.io/v1/
 Labels:
  provider=amazonec2
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.9.6
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
```

While this is running on docker swarm on AWS I have been able to replicate the problem locally if i locally clone the setup (include DB and other data).

## some additional info

When the above fails when trying to load through the built-in bitnami scripts I decided to spinup the container and run the rake db:migrate command manually and I actually got some useful output.

```
root@247906f3a823:/opt/bitnami/discourse# bundle exec rake db:migrate
** PLUGIN FAILURE **

You are unable to build Discourse due to this error during plugin
initialization:

uninitialized constant Plugin::Instance::DiscourseDev

/opt/bitnami/discourse/lib/plugin/instance.rb:98:in `block in find_all'
/opt/bitnami/discourse/lib/plugin/instance.rb:86:in `tap'
/opt/bitnami/discourse/lib/plugin/instance.rb:86:in `find_all'
lib/discourse.rb:243:in `activate_plugins!'
/opt/bitnami/discourse/config/application.rb:312:in `block in <class:Application>'
/opt/bitnami/discourse/lib/plugin_initialization_guard.rb:5:in `plugin_initialization_guard'
/opt/bitnami/discourse/config/application.rb:311:in `<class:Application>'
/opt/bitnami/discourse/config/application.rb:73:in `<module:Discourse>'
/opt/bitnami/discourse/config/application.rb:72:in `<top (required)>'
/opt/bitnami/discourse/Rakefile:7:in `require'
/opt/bitnami/discourse/Rakefile:7:in `<top (required)>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load_rakefile'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:703:in `raw_load_rakefile'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'
/opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:28:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/cli.rb:474:in `exec'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/cli.rb:30:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/cli.rb:24:in `start'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/exe/bundle:49:in `block in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/exe/bundle:37:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
```

**Comment by freemo** [comment]
As per my own findings it turned out one or more of my plugins were out of date. Once I did a git pull on all of them everything started working again.

Seems the bug on bitnami's side is the fact that when the db:migrate step errors and would normally output a useful error this container silently fails instead making debugging very difficult.

**Comment by juan131** [comment]
Hi @freemo 

Thanks so much for opening this issue!! Also, I'm very glad you were able to solve the issue by updating the plugins. 

Please note that we highly discourage using rolling tags for production environments, since you don't have control of the exact image revision you're. Learn more about this topic in the link below:

- https://github.com/bitnami/bitnami-docker-discourse#supported-tags-and-respective-dockerfile-links

Regarding the verbosity of the logs, please note that you can increase it by setting the environment variable `BITNAMI_DEBUG=1` in the Discourse containers. Using that env. var. the output of the rake command should be displayed.

I proceed to close this issue as "solved" since you could workaround it updating your plugins. Please don't hesitate to reopen it if you require further help.

**Comment by karpfediem** [comment]
Thanks for the hint using `BITNAMI_DEBUG=1`!

This is still an issue i was facing using the current (7.2.3) bitnami discourse helm chart (https://github.com/bitnami/charts/tree/master/bitnami/discourse/)

In my case my database password was not escaped properly and resulted in an authentication error against the database.
The setup script (this docker's entrypoint: `/opt/bitnami/scripts/discourse/entrypoint.sh /opt/bitnami/scripts/discourse/run.sh`) silently fails with exit code 1 without of displaying any information past `Populating database`.

The exact command in question would be `bundle exec rake db:migrate` as called by [discourse_initialize()](https://github.com/bitnami/bitnami-docker-discourse/blob/b433ce835903a33d0957d7c61cde9d5d20ca3a7a/2/debian-10/rootfs/opt/bitnami/scripts/libdiscourse.sh#L165)

Since an actual error occurs this should also be presented back to the user and not swallowed away under debug exclusive output.
