### ISSUE TITLE
Fail to export topic

### ISSUE THREAD

**Issue by bertrandgorge** [bitnami/bitnami-docker-discourse#206]
**Description**

Hello, I try to follow the procedure to export / import topics from https://meta.discourse.org/t/topic-and-category-export-import/38930

I figure the discourse script in question is the following, but then I get this error when launching:

```
root@7778147c7c4d:/opt/bitnami/discourse/script# ./discourse export_topics 18
Traceback (most recent call last):
        2: from ./discourse:4:in `<main>'
        1: from /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- thor (LoadError)

```
**Steps to reproduce the issue:**

1. docker-compose exec discourse bash
2. cd /opt/bitnami/discourse/script
3. ./discourse export_topics 18

**Version**

- image : 2.7.8-debian-10-r0
- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)
WARNING: Plugin "/usr/libexec/docker/cli-plugins/docker-app" is not valid: failed to fetch metadata: fork/exec /usr/libexec/docker/cli-plugins/docker-app: no such file or directory

Server:
 Containers: 21
  Running: 14
  Paused: 0
  Stopped: 7
 Images: 47
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 5.801GiB
 Name: docker-desktop
 ID: ZHFO:ZN2W:U5PW:D3WD:Q4BY:3WAG:FRHU:MJ3Y:3VU2:GEAM:E6FQ:6FST
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
Docker Compose version v2.0.0-rc.3
```

**Comment by marcosbc** [comment]
Hi @bertrandgorge, have you tried to enable the script with `RAILS_ENV=production`?

```
$ RAILS_ENV=production ./discourse export_topics 18
```

**Comment by bertrandgorge** [comment]
Hello @marcosbc - thanks ! Just tried right now, and it didn't change anything, I'm still having the same error. Does it work on your end ?

**Comment by marcosbc** [comment]
Hi @bertrandgorge, sorry, you seem to be right as that is still not loading the bundler environment.

The correct command is:

```
$ RAILS_ENV=production bundle exec ruby script/discourse export_topics 18
```

I verified that it works on my side. Let us know if you continue to find issues.

**Comment by bertrandgorge** [comment]
Ahhhh... Ok it works with your command.... Got it... Thanks a million!
