### ISSUE TITLE
Create a project through docker-compose, the project cannot be accessed

### ISSUE THREAD

**Issue by yangjunjie52** [bitnami/bitnami-docker-discourse#222]
### Name and Version

latest

### What steps will reproduce the bug?

1.keep going to download - rubyext-ruby-2.7.5-x86_64-linux.tar.gz。but can't find
2.After accessing the address, the page is blank and the console reports an error
3.what should I do？

### What do you see instead?

```console
discourse 16:29:13.79 INFO  ==> ** Starting Discourse **
discourse_1   |  [passenger_native_support.so] trying to compile for the current user (root) and Ruby interpreter...
discourse_1   |      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1   |      Warning: compilation didn't succeed. To learn why, read this file:
discourse_1   |      /tmp/passenger_native_support-70k3tz.log
discourse_1   |  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
discourse_1   |      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1   |      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz: Operation too slow. Less than 1 bytes/sec transferred the last 5 seconds
discourse_1   |      Trying next mirror...
discourse_1   |      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz: The requested URL returned error: 404
discourse_1   |      Trying next mirror...
discourse_1   |      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
discourse_1   |  [passenger_native_support.so] will not be used (can't compile or download)
discourse_1   |   --> Passenger will still operate normally.
discourse_1   | =============== Phusion Passenger(R) Standalone web server started ===============
discourse_1   | PID file: /opt/bitnami/discourse/passenger.3000.pid
discourse_1   | Log file: /opt/bitnami/discourse/log/passenger.3000.log
discourse_1   | Environment: production
discourse_1   | Accessible via: http://0.0.0.0:3000/
discourse_1   |
discourse_1   | You can stop Phusion Passenger(R) Standalone by pressing Ctrl-C.
discourse_1   | Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
discourse_1   | ===============================================================================
discourse_1   | [ N 2022-02-10 16:29:33.6702 567/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
discourse_1   | App 606 output:  [passenger_native_support.so] trying to compile for the current user (discourse) and Ruby interpreter...
discourse_1   | App 606 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1   | App 606 output:      Warning: compilation didn't succeed. To learn why, read this file:
discourse_1   | App 606 output:      /tmp/passenger_native_support-g9rxqh.log
discourse_1   | App 606 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
discourse_1   | App 606 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1   | App 606 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz: Connection timed out after 4001 milliseconds
discourse_1   | App 606 output:      Trying next mirror...
discourse_1   | App 606 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz: The requested URL returned error: 404
discourse_1   | App 606 output:      Trying next mirror...
discourse_1   | App 606 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
discourse_1   | App 606 output:  [passenger_native_support.so] will not be used (can't compile or download)
discourse_1   | App 606 output:   --> Passenger will still operate normally.
discourse_1   | Creating scope :open. Overwriting existing method Poll.open.
discourse_1   | Started HEAD "/" for 127.0.0.1 at 2022-02-10 16:30:00 +0000
discourse_1   | Processing by ListController#latest as HTML
discourse_1   |   Rendered list/list.erb within layouts/crawler (Duration: 43.0ms | Allocations: 12258)
discourse_1   |   Rendered layout layouts/crawler.html.erb (Duration: 178.1ms | Allocations: 34182)
```

**Comment by juan131** [comment]
Hi @yangjunjie52 

Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by yangjunjie52** [comment]
I went into the container to check the log and found that because the following command could not be found, the container tried to download 2.7.5

/opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:613:in `try_cpp'
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:1124:in `block in have_header'
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:331:in `open'
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:331:in `open'
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
        from /opt/bitnami/ruby/lib/ruby/2.7.0/mkmf.rb:1123:in `have_header'
        from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/passenger-6.0.12/src/ruby_native_extension/extconf.rb:45:in `<main>'
root@c5ec49ef216c:/bitnami/discourse/public# cd /opt/bitnami/ruby/lib/ruby/2.7.0/
