### ISSUE TITLE
Sidekiq fails to start

### ISSUE THREAD

**Issue by Southclaws** [bitnami/bitnami-docker-discourse#52]
**Description**

Sidekiq fails to start with some unhelpful errors:

**Steps to reproduce the issue:**

Just deploy the example docker-compose.yml, I got it from the docker hub page and the readme here.

**Describe the results you received:**

```
sidekiq_1     | Welcome to the Bitnami discourse container
sidekiq_1     | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
sidekiq_1     | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
sidekiq_1     |
sidekiq_1     | Starting discourse-sidekiq...
sidekiq_1     | /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
sidekiq_1     | /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
sidekiq_1     | /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/cli.rb:27:in `dispatch'
sidekiq_1     | /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
sidekiq_1     | /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/cli.rb:18:in `start'
sidekiq_1     | /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/exe/bundle:30:in `block in <top (required)>'
sidekiq_1     | /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
sidekiq_1     | /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/exe/bundle:22:in `<top (required)>'
sidekiq_1     | /opt/bitnami/discourse-sidekiq/bin/bundle:104:in `load'
sidekiq_1     | /opt/bitnami/discourse-sidekiq/bin/bundle:104:in `<main>'
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I found the docs a bit lacking, there are some variables missing which I only knew about by browsing through issues, like `POSTGRESQL_CLIENT_CREATE_DATABASE_NAME`. Am I missing anything else?

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running on a macbook but intend to deploy to an Ubuntu server running Docker 17

**Comment by juan131** [comment]
Hi @Southclaws 

I was unable to reproduce it on Ubuntu. Could you try the sequence below?

```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-discourse/master/docker-compose.yml > docker-compose.yml
$ docker-compose down --rmi all
$ docker-compose up -d 
$ docker-compose logs -f sidekiq
Attaching to tmp_sidekiq_1
sidekiq_1     |
sidekiq_1     | Welcome to the Bitnami discourse container
sidekiq_1     | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
sidekiq_1     | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
sidekiq_1     |
sidekiq_1     | nami    INFO  Initializing discourse-sidekiq
sidekiq_1     | postgre INFO  Trying to connect to PostgreSQL server
sidekiq_1     | postgre INFO  Found PostgreSQL server listening at postgresql:5432
sidekiq_1     | postgre INFO  PostgreSQL server listening and working at postgresql:5432
sidekiq_1     | discour INFO  Configuring the Discourse database files...
sidekiq_1     | discour INFO  Configuring Redis...
sidekiq_1     | discour INFO  Setting up SMTP in Sidekiq...
sidekiq_1     | discour INFO  Waiting for Discourse service to be ready...
sidekiq_1     | nami    INFO  discourse-sidekiq successfully initialized
sidekiq_1     | Starting discourse-sidekiq...
sidekiq_1     | # Logfile created on 2018-09-03 09:04:57 +0000 by logger.rb/56815
sidekiq_1     | 2018-09-03T09:05:02.966Z 87 TID-gp41w4suj INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :namespace=>"sidekiq", :id=>"Sidekiq-server-PID-87", :url=>nil}
```

**Comment by Southclaws** [comment]
Turns out the config doesn't regenerate so making changes to the environment variables was having no effect. I had to manually modify the .conf files for both Discourse and Sidekiq in my mounted directories.

**Comment by juan131** [comment]
Hi @Southclaws 

Yes.. As you mentioned those env. variables are only considered if there's no persisted data/configuration to be used. 

I am glad you could fix the issue by editing the configuration files. Please feel free to open a new issue if you have any other problem with this image.
