### ISSUE TITLE
Best tutorial for local development

### ISSUE THREAD

**Issue by vsoch** [bitnami/bitnami-docker-discourse#61]
hey bitnami!

Using the docker-compose obtained with curl from Docker Hub, it looks like local is used for several things, including a "sidekiq-data." However my local machine doesn't have sendmail, this is the log I see for the main container (on port 3000):

```
# Logfile created on 2018-11-20 17:51:36 +0000 by logger.rb/56815
2018-11-20T17:51:42.802Z 90 TID-gso9l7o5q INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :namespace=>"sidekiq", :id=>"Sidekiq-server-PID-90", :url=>nil}
sh: 1: /usr/sbin/sendmail: not found
```
What would you suggest as a deployment that doesn't rely on anything locally? I basically want to bring up a dummy instance to install and test themes on (that are generated on the theme site) so likely I'll edit it to mirror my group's discourse, and then give them instructions for testing out a new theme (before deploying to production). Thanks for your help!

**Comment by prydonius** [comment]
@vsoch ah my bad - I just transferred this issue to the discourse repository. From your log, it looks like only sidekiq is failing, are the other containers (discourse, postgres, redis) running okay?

**Comment by vsoch** [comment]
I love the new issue transfer (beta) feature! Let's check on the other containers too. They are definitely running, but it's good that we also look at the logs. Here is the overall set:

```bash
$ docker-compose ps
            Name                          Command               State          Ports        
--------------------------------------------------------------------------------------------
discourse-theme_discourse_1    /app-entrypoint.sh nami st ...   Up      0.0.0.0:80->3000/tcp
discourse-theme_postgresql_1   /app-entrypoint.sh /run.sh       Up      5432/tcp            
discourse-theme_redis_1        /entrypoint.sh /run.sh           Up      6379/tcp            
discourse-theme_sidekiq_1      /app-entrypoint.sh nami st ...   Up      3000/tcp   
```

Here is the complete logs (`docker-compose logs > logs.txt`) Thanks for your help!
[logs.txt](https://github.com/bitnami/bitnami-docker-discourse/files/2601892/logs.txt)

**Comment by prydonius** [comment]
> I love the new issue transfer (beta) feature!

+1 it's so handy!

Thanks a lot for the logs, it does look like Discourse might have had trouble connecting to Postgres from those logs, do you see anything at all when you go to `http://localhost` in your browser?

**Comment by vsoch** [comment]
There is an error message now! I wonder if the start up took some delay and I didn't see it before. I also was trying port 3000 and (still don't) see anything there.

![image](https://user-images.githubusercontent.com/814322/48810042-1f3c7a80-ecf5-11e8-87fd-b740ede0ca53.png)

It does seem to be some issue with this sidekq container? What is that exactly?

```bash
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
/opt/bitnami/discourse-sidekiq/config/environment.rb:5:in `<top (required)>'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/cli.rb:272:in `require'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/cli.rb:272:in `boot_system'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/cli.rb:53:in `run'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/bin/sidekiq:12:in `<top (required)>'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/bin/sidekiq:23:in `load'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.4.0/bin/sidekiq:23:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/opt/bitnami/discourse-sidekiq/bin/bundle:104:in `load'
/opt/bitnami/discourse-sidekiq/bin/bundle:104:in `<main>'
```

**Comment by prydonius** [comment]
Sidekiq is a background processor (for things like sending emails) so I _think_ Discourse should work fine without it running, and you won't really need it if you're only interested in having something local to test themes. Someone from the team that's more knowledgeable about Discourse might have more info, though.

Would you be able to run the following commands:
```
docker-compose rm -s -f discourse
docker-compose up
```

Wait for the discourse container to come up and then get the logs from it:

```
docker-compose logs discourse
```

This should help us understand better what might be happening in discourse.

**Comment by vsoch** [comment]
Without doing `docker compose up -d` (note the d for detached) I can't then run docker-compose logs discourse, so I ran this in a different terminal (looks okay to me)

```bash
$ docker-compose logs -f discourse
Attaching to discourse-theme_discourse_1
discourse_1   | 
discourse_1   | Welcome to the Bitnami discourse container
discourse_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse_1   | 
discourse_1   | nami    INFO  Initializing postgresql-client
discourse_1   | postgre INFO  Trying to connect to PostgreSQL server
discourse_1   | postgre INFO  Found PostgreSQL server listening at postgresql:5432
discourse_1   | postgre INFO  PostgreSQL server listening and working at postgresql:5432
discourse_1   | nami    INFO  postgresql-client successfully initialized
discourse_1   | nami    INFO  Initializing discourse
discourse_1   | discour INFO  Patching Discourse...
discourse_1   | postgre INFO  Trying to connect to PostgreSQL server
discourse_1   | postgre INFO  Found PostgreSQL server listening at postgresql:5432
discourse_1   | postgre INFO  PostgreSQL server listening and working at postgresql:5432
discourse_1   | discour INFO  Migrating database...
discourse_1   | discour INFO 
discourse_1   | discour INFO  ########################################################################
discourse_1   | discour INFO   Installation parameters for discourse:
discourse_1   | discour INFO     Persisted data and properties have been restored.
discourse_1   | discour INFO     Any input specified will not take effect.
discourse_1   | discour INFO   This installation requires no credentials.
discourse_1   | discour INFO  ########################################################################
discourse_1   | discour INFO 
discourse_1   | nami    INFO  discourse successfully initialized
discourse_1   | Starting discourse...
discourse_1   | [ N 2018-11-21 00:49:55.3071 2822/T1 age/Wat/WatchdogMain.cpp:1366 ]: Starting Passenger watchdog...
discourse_1   | [ N 2018-11-21 00:49:55.3220 2825/T1 age/Cor/CoreMain.cpp:1310 ]: Starting Passenger core...
discourse_1   | [ N 2018-11-21 00:49:55.3221 2825/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
discourse_1   | [ N 2018-11-21 00:49:55.3348 2825/T1 age/Cor/CoreMain.cpp:985 ]: Passenger core online, PID 2825
discourse_1   | [ N 2018-11-21 00:49:57.9335 2825/T5 age/Cor/SecurityUpdateChecker.h:517 ]: Security update check: no update found (next check in 24 hours)
discourse_1   | Started HEAD "/" for 127.0.0.1 at 2018-11-21 00:50:07 +0000
discourse_1   | Processing by ListController#latest as HTML
discourse_1   |   Rendering list/list.erb within layouts/application
discourse_1   |   Rendered list/list.erb within layouts/application (27.5ms)
discourse_1   |   Rendered layouts/_head.html.erb (103.1ms)
discourse_1   |   Rendered common/_discourse_stylesheet.html.erb (4.2ms)
discourse_1   |   Rendered common/_special_font_face.html.erb (1.0ms)
discourse_1   |   Rendered application/_header.html.erb (1.7ms)
discourse_1   |   Rendered common/_discourse_javascript.html.erb (229.2ms)
discourse_1   | Completed 200 OK in 677ms (Views: 366.9ms | ActiveRecord: 96.2ms)
```
I then went to the interface to see if that triggered something:

Aaand it worked!

![image](https://user-images.githubusercontent.com/814322/48812417-43518900-ed00-11e8-94a4-6af9fc61b5d3.png)

So I can't reproduce my own error - it must have been some conflict with another container that I was running (I stopped all containers that were running to test) so likely this is user error. Thanks for the help - we can close the issue and I'll reopen if I run into anything else! :+1:

**Comment by carrodher** [comment]
Hi @vsoch, the current user should be `user` (as you rightly said) and the password `bitnami123`, you can find more information about the variables and their default value in the README:
https://github.com/bitnami/bitnami-docker-discourse#environment-variables

Have these values worked for you?

**Comment by vsoch** [comment]
Affirmative! Thanks muchly. In the docker compose file that I used, the password seems to be turned off (so it still exists for the "user" user but isn't set via config). 

```yaml
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
```

I thought that leaving the password empty might work, but it didn't need to. I'll also add this to the README in ours docs, thanks again. :L)

**Comment by carrodher** [comment]
Hi, this env variable is applied to the `redis` container not to the `discourse` one
```yaml
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
```

`ALLOW_EMPTY_PASSWORD` can be used to allow blank passwords but not in the main container (the application itself), it is designed to be used in the dependent containers such as `redis`, databases, etc. In this way, you can connect the main container to the other ones without specifying a password
