### ISSUE TITLE
Backup Failed

### ISSUE THREAD

**Issue by matthewpomar** [bitnami/bitnami-docker-discourse#65]
**Description**

While performing a backup on a newly setup Bitnami Discourse image, I get an error stating the backup failed. Here are the logs:

```
[2019-01-05 17:01:15] 'user' has started the backup!
[2019-01-05 17:01:15] Marking backup as running...
[2019-01-05 17:01:15] Making sure '/opt/bitnami/discourse/tmp/backups/default/2019-01-05-170115' exists...
[2019-01-05 17:01:15] Making sure '/opt/bitnami/discourse/public/backups/default' exists...
[2019-01-05 17:01:15] Pausing sidekiq...
[2019-01-05 17:01:15] Waiting for sidekiq to finish running jobs...
[2019-01-05 17:01:15] Dumping the public schema of the database...
[2019-01-05 17:01:15] pg_dump: server version: 10.6; pg_dump version: 9.6.11
[2019-01-05 17:01:15] EXCEPTION: pg_dump failed
[2019-01-05 17:01:15] /opt/bitnami/discourse/lib/backup_restore/backuper.rb:172:in `dump_public_schema'
/opt/bitnami/discourse/lib/backup_restore/backuper.rb:37:in `run'
/opt/bitnami/discourse/lib/backup_restore/backup_restore.rb:167:in `block in start!'
/opt/bitnami/discourse/lib/backup_restore/backup_restore.rb:164:in `fork'
/opt/bitnami/discourse/lib/backup_restore/backup_restore.rb:164:in `start!'
/opt/bitnami/discourse/lib/backup_restore/backup_restore.rb:18:in `backup!'
/opt/bitnami/discourse/app/controllers/admin/backups_controller.rb:32:in `create'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:194:in `process_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:132:in `run_callbacks'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:134:in `process'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.0/lib/action_view/rendering.rb:32:in `process'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-mini-profiler-1.0.0/lib/mini_profiler/profiling_methods.rb:78:in `block in profile_method'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_controller/metal.rb:191:in `dispatch'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_controller/metal.rb:252:in `dispatch'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `serve'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:840:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/frame_options.rb:31:in `call'
/opt/bitnami/discourse/lib/middleware/omniauth_bypass_middleware.rb:24:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/opt/bitnami/discourse/lib/middleware/anonymous_cache.rb:214:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:98:in `run_callbacks'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/logster-1.2.11/lib/logster/middleware/reporter.rb:31:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:38:in `call_app'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:28:in `call'
/opt/bitnami/discourse/config/initializers/100-quiet_logger.rb:16:in `call'
/opt/bitnami/discourse/config/initializers/100-silence_logger.rb:29:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/opt/bitnami/discourse/lib/middleware/enforce_hostname.rb:17:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-mini-profiler-1.0.0/lib/mini_profiler/profiler.rb:174:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/message_bus-2.1.5/lib/message_bus/rack/middleware.rb:63:in `call'
/opt/bitnami/discourse/lib/middleware/request_tracker.rb:180:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:524:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/urlmap.rb:68:in `block in call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.0/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.0/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.0/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.0/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/opt/bitnami/discourse/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.0/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
[2019-01-05 17:01:15] Notifying 'user' of the end of the backup...
[2019-01-05 17:01:18] Removing old backups...
[2019-01-05 17:01:18] Cleaning stuff up...
[2019-01-05 17:01:18] Removing '.tar' leftovers...
[2019-01-05 17:01:18] Unpausing sidekiq...
[2019-01-05 17:01:18] Marking backup as finished...
[2019-01-05 17:01:18] Refreshing disk cache...
[2019-01-05 17:01:18] Finished!
```

**Steps to reproduce the issue:**

1. Log into Discourse
2. Go to Admin settings, the Backup
3. Click backup

**Describe the results you received:**

I starts the backup, and after the logs run for a bit, get's to the line where it says `Notifying 'user' of the end of the backup...` where it sits there for a while, then finishes/fails.

**Describe the results you expected:**

I expect full backup to complete.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm using Synology Docker, but not sure this is relevant.
I've also not configured SMTP settings for this server yet, but not sure this is relevant.
Lastly, I have not setup Sidekiq yet, but not sure this is relevant.

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Thu Oct 11 21:32:14 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Thu Oct 11 21:32:14 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 9
 Running: 6
 Paused: 0
 Stopped: 3
Images: 32
Server Version: 17.05.0-ce
Storage Driver: btrfs
Logging Driver: db
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: fd189da3e13a3ef3d6d9eb73c5cd4697b4536cdd (expected: 9048e5e50717ea4497b757314bad98ea3763c145)
runc version: a2d6e07aab95ff37fb63cf5dec3c40d29940194f (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: 7a83305 (expected: 949e6fa)
Security Options:
 apparmor
Kernel Version: 3.10.102
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66GiB
Name: Hubcap
ID: BEP7:JEOM:RLT3:VHU7:A3IZ:FZJP:PQQ6:P7OD:GS73:2IUL:H4PL:V72R
Docker Root Dir: /volume1/@docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi @matthewpomar ,
  Could you provide the docker command that you use to run discourse ?

Thanks forehand
Rafael Rios Saavedra

**Comment by matthewpomar** [comment]
Hi Rafael. Since I'm using Synology, I just press the Start button, but I believe the command it uses is:

`/app-entrypoint.sh nami start --foreground discourse`

**Comment by tompizmor** [comment]
Hi @matthewpomar,

I tried deploying Discourse with this [docker-compose file](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-9/docker-compose.yml) and the backup functionality worked fine. 

The backup log mentions Sidekiq a couple of times so I think it might be required. Please take a look to my logs:

```
[2019-01-08 16:01:13] 'user' has started the backup!
[2019-01-08 16:01:13] Marking backup as running...
[2019-01-08 16:01:13] Making sure '/opt/bitnami/discourse/tmp/backups/default/2019-01-08-160113' exists...
[2019-01-08 16:01:13] Making sure '/opt/bitnami/discourse/public/backups/default' exists...
[2019-01-08 16:01:13] Pausing sidekiq...
[2019-01-08 16:01:13] Waiting for sidekiq to finish running jobs...
[2019-01-08 16:01:13] Dumping the public schema of the database...
[2019-01-08 16:01:13] pg_dump: last built-in OID is 16383
[2019-01-08 16:01:13] pg_dump: reading extensions
[2019-01-08 16:01:13] pg_dump: identifying extension members
[2019-01-08 16:01:13] pg_dump: reading schemas
[2019-01-08 16:01:13] pg_dump: reading user-defined tables
[2019-01-08 16:01:13] pg_dump: reading user-defined functions
[2019-01-08 16:01:13] pg_dump: reading user-defined types
[2019-01-08 16:01:13] pg_dump: reading procedural languages
[2019-01-08 16:01:13] pg_dump: reading user-defined aggregate functions
[2019-01-08 16:01:13] pg_dump: reading user-defined operators
[2019-01-08 16:01:13] pg_dump: reading user-defined access methods
[2019-01-08 16:01:13] pg_dump: reading user-defined operator classes
[2019-01-08 16:01:13] pg_dump: reading user-defined operator families
[2019-01-08 16:01:13] pg_dump: reading user-defined text search parsers
[2019-01-08 16:01:13] pg_dump: reading user-defined text search templates
[2019-01-08 16:01:13] pg_dump: reading user-defined text search dictionaries
[2019-01-08 16:01:13] pg_dump: reading user-defined text search configurations
[2019-01-08 16:01:13] pg_dump: reading user-defined foreign-data wrappers
[2019-01-08 16:01:13] pg_dump: reading user-defined foreign servers
[2019-01-08 16:01:13] pg_dump: reading default privileges
[2019-01-08 16:01:13] pg_dump: reading user-defined collations
[2019-01-08 16:01:13] pg_dump: reading user-defined conversions
[2019-01-08 16:01:13] pg_dump: reading type casts
[2019-01-08 16:01:13] pg_dump: reading transforms
[2019-01-08 16:01:13] pg_dump: reading table inheritance information
[2019-01-08 16:01:13] pg_dump: reading event triggers
[2019-01-08 16:01:13] pg_dump: finding extension tables
[2019-01-08 16:01:13] pg_dump: finding inheritance relationships
[2019-01-08 16:01:13] pg_dump: reading column info for interesting tables
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.schema_migrations"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.ar_internal_metadata"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.schema_migration_details"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.schema_migration_details"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.topics"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.topics"
[2019-01-08 16:01:13] pg_dump: finding check constraints for table "public.topics"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.posts"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.posts"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.users"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.users"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.topic_views"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.uploads"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.uploads"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.topic_users"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.topic_users"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.topic_links"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.topic_links"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.post_timings"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.message_bus"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.message_bus"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.notifications"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.notifications"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.incoming_links"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.incoming_links"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.post_replies"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.categories"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.categories"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.category_featured_topics"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.category_featured_topics"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.site_settings"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.site_settings"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.user_open_ids"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.user_open_ids"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.user_actions"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.user_actions"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.post_actions"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.post_actions"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.post_action_types"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.post_action_types"
[2019-01-08 16:01:13] pg_dump: finding the columns and types of table "public.topic_link_clicks"
[2019-01-08 16:01:13] pg_dump: finding default expressions of table "public.topic_link_clicks"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.search_logs_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.shared_drafts"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.shared_drafts_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.shared_drafts_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.single_sign_on_records"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.single_sign_on_records_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.single_sign_on_records_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.site_settings"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.site_settings_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.site_settings_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.skipped_email_logs"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.skipped_email_logs_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.skipped_email_logs_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.stylesheet_cache"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.stylesheet_cache_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.stylesheet_cache_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.tag_group_memberships"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.tag_group_memberships_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.tag_group_memberships_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.tag_group_permissions"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.tag_group_permissions_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.tag_group_permissions_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.tag_groups"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.tag_groups_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.tag_groups_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.tag_search_data"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.tag_search_data_tag_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.tag_search_data_tag_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.tag_users"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.tag_users_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.tag_users_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.tags"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.tags_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.tags_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.theme_fields"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.theme_fields_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.theme_fields_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.theme_settings"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.theme_settings_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.theme_settings_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.themes"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.themes_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.themes_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.top_topics"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.top_topics_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.top_topics_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_allowed_groups"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_allowed_groups_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_allowed_groups_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_allowed_users"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_allowed_users_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_allowed_users_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_custom_fields"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_custom_fields_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_custom_fields_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_embeds"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_embeds_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_embeds_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_invites"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_invites_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_invites_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_link_clicks"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_link_clicks_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_link_clicks_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_links"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_links_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_links_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_search_data"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_search_data_topic_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_search_data_topic_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_tags"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_tags_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_tags_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_timers"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_timers_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_timers_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_users"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topic_users_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topic_users_id_seq"
[2019-01-08 16:01:14] pg_dump: creating TABLE "public.topic_views"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE "public.topics_id_seq"
[2019-01-08 16:01:14] pg_dump: creating SEQUENCE OWNED BY "public.topics_id_seq"
[2019-01-08 16:01:14] Finalizing backup...
[2019-01-08 16:01:14] Creating archive: my-site-2019-01-08-160113-v20180920042415.tar.gz
[2019-01-08 16:01:14] Making sure archive does not already exist...
[2019-01-08 16:01:14] Creating empty archive...
[2019-01-08 16:01:14] Archiving data dump...
[2019-01-08 16:01:14] Archiving uploads...
[2019-01-08 16:01:14] Removing tmp '/opt/bitnami/discourse/tmp/backups/default/2019-01-08-160113' directory...
[2019-01-08 16:01:14] Gzipping archive, this may take a while...
[2019-01-08 16:01:15] Executing the after_create_hook for the backup...
[2019-01-08 16:01:15] Notifying 'user' of the end of the backup...
[2019-01-08 16:01:18] Removing old backups...
[2019-01-08 16:01:18] Cleaning stuff up...
[2019-01-08 16:01:18] Removing '.tar' leftovers...
[2019-01-08 16:01:18] Unpausing sidekiq...
[2019-01-08 16:01:18] Marking backup as finished...
[2019-01-08 16:01:18] Refreshing disk cache...
[2019-01-08 16:01:18] Finished!
```
