### ISSUE TITLE
Problem with starting discourse

### ISSUE THREAD

**Issue by pcellix** [bitnami/bitnami-docker-discourse#85]
Hi All

While trying to start discourse I got the following log:

```
nami    TRACE Error: Error executing 'postInstallation': I, [2019-05-03T19:54:10.230688 #1197]  INFO -- : Writing /opt/bitnami/discourse/public/assets/vendor-3eae3eec8fba033cb1b5af6c103a5b8781caa69cf97fe7773ba89ba68980b263.js
I, [2019-05-03T19:54:21.741925 #1197]  INFO -- : Writing /opt/bitnami/discourse/public/assets/admin-11463cb9cb192a2bb9af42cd03f097545a6a5c3ce54517383063d9000abaa14e.js
I, [2019-05-03T19:54:21.784937 #1197]  INFO -- : Writing /opt/bitnami/discourse/public/assets/preload-store-081120a9f8cb0871483b66a95e534ce8e81f97d19c8cef978aea6c696d1feb20.js
I, [2019-05-03T19:54:23.219398 #1197]  INFO -- : Writing /opt/bitnami/discourse/public/assets/browser-update-d924ff41586d6dcda055f0cfb41488724ba2e2d5271fef65ce5f480b46f9231d.js
I, [2019-05-03T19:54:23.228497 #1197]  INFO -- : Writing /opt/bitnami/discourse/public/assets/break_string-cc617154cd957804f2f6a1f3bc68258c9cdca3d4b9a322bf777d145fed04790e.js

    at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
    at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
    at Object.$app.helpers.execute (/root/.nami/components/com.bitnami.ruby/helpers.js:44:7)
    at Object.$app.helpers.bundleExecute (/root/.nami/components/com.bitnami.ruby/helpers.js:62:8)
    at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
    at Service.$app.postInstallation (/root/.nami/components/com.bitnami.discourse/main.js:70:8)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
```

My docker-compose is exactly the same as in debian directory of this repo

Thank you very much for your help :)

**Comment by marcosbc** [comment]
Hi @pcellix, unfortunately we're unable to reproduce your issue with the same `docker-compose.yml` file.

It seems like your compose is failing at the stage for precompiling assets, but we're not fully certain of this. Could you send us the full initialization logs?

Also, in order to add more debug, modify your docker-compose.yml in the following way:

```
@@ -20,6 +20,7 @@
     volumes:
       - 'discourse_data:/bitnami'
     environment:
+      - NAMI_LOG_LEVEL=trace8
       - POSTGRESQL_HOST=postgresql
       - POSTGRESQL_ROOT_USER=postgres
       - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
```

**Comment by pcellix** [comment]
@marcosbc  
sorry for late response
I was super busy
Thank you for looking into the issue :)
File attached

**Comment by pcellix** [comment]
[logerror.txt](https://github.com/bitnami/bitnami-docker-discourse/files/3266919/logerror.txt)

**Comment by pcellix** [comment]
@marcosbc  could you please reopen the issue as i have no rights to do so
Thank you :)

**Comment by marcosbc** [comment]
Hi @pcellix, unfortunately we still cannot reproduce your issue. It is failing generating assets.

Was your Discourse container initialized before (e.g. it had data)? If yes, could you try to launch a clean container and check if it works?

If it works, we recommend you to compare the configuration files in `/opt/bitnami/discourse/conf` in case there is any significant difference.
