### ISSUE TITLE
pass store is uninitialized

### ISSUE THREAD

**Issue by Fruchtgummi** [bitnami/bitnami-docker-discourse#92]
The error by docker-compose up -d

`
Creating network "disco_default" with the default driver
Creating volume "disco_discourse_data" with local driver
Creating volume "disco_postgresql_data" with local driver
Creating volume "disco_sidekiq_data" with local driver
Creating volume "disco_redis_data" with local driver
Pulling redis (bitnami/redis:5.0)...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 431, in up
    svc.ensure_image_exists(do_build=do_build)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 312, in ensure_image_exists
    self.pull()
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 1029, in pull
    output = self.client.pull(repo, tag=tag, stream=True)
  File "/usr/lib/python2.7/dist-packages/docker/api/image.py", line 381, in pull
    header = auth.get_config_header(self, registry)
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 50, in get_config_header
    authcfg = resolve_authconfig(client._auth_configs, registry)
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 97, in resolve_authconfig
    authconfig, registry, store_name
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 142, in _resolve_authconfig_credstore
    'Credentials store error: {0}'.format(repr(e))
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-pass exited with "pass store is uninitialized".',)

`

I do not understand my problem! You can help?

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I used the default docker-compose.yml and it worked

```
postgresql_1  |
postgresql_1  | Welcome to the Bitnami postgresql container
postgresql_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
redis_1       |
redis_1       | Welcome to the Bitnami redis container
redis_1       | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis_1       | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis_1       | Send us your feedback at containers@bitnami.com
redis_1       |
redis_1       | INFO  ==> ** Starting Redis setup **
redis_1       | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
discourse_1   |
redis_1       | INFO  ==> Initializing Redis...
postgresql_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql_1  | Send us your feedback at containers@bitnami.com
postgresql_1  |
postgresql_1  | INFO  ==> ** Starting PostgreSQL setup **
postgresql_1  | INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
postgresql_1  | INFO  ==> Initializing PostgreSQL database...
redis_1       |
redis_1       | INFO  ==> ** Redis setup finished! **
redis_1       | INFO  ==> ** Starting Redis **
discourse_1   | Welcome to the Bitnami discourse container
postgresql_1  | INFO  ==> postgresql.conf file not detected. Generating it...
postgresql_1  | INFO  ==> pg_hba.conf file not detected. Generating it...
discourse_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
discourse_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
discourse_1   |
redis_1       | 1:C 17 Jun 2019 20:42:51.346 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1       | 1:C 17 Jun 2019 20:42:51.346 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1       | 1:C 17 Jun 2019 20:42:51.346 # Configuration loaded
redis_1       |                 _._
redis_1       |            _.-``__ ''-._
redis_1       |       _.-``    `.  `_.  ''-._           Redis 5.0.5 (00000000/0) 64 bit
redis_1       |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1       |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1       |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1       |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1       |   `-._    `-._  `-./  _.-'    _.-'
redis_1       |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1       |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1       |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1       |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1       |  |    `-._`-._        _.-'_.-'    |
redis_1       |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1       |       `-._    `-.__.-'    _.-'
redis_1       |           `-._        _.-'
redis_1       |               `-.__.-'
redis_1       |
redis_1       | 1:M 17 Jun 2019 20:42:51.352 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1       | 1:M 17 Jun 2019 20:42:51.353 # Server initialized
redis_1       | 1:M 17 Jun 2019 20:42:51.354 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1       | 1:M 17 Jun 2019 20:42:51.354 * Ready to accept connections
sidekiq_1     |
sidekiq_1     | Welcome to the Bitnami discourse container
sidekiq_1     | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
sidekiq_1     | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
sidekiq_1     |
postgresql_1  | INFO  ==> Starting PostgreSQL in background...
postgresql_1  | /tmp:5432 - accepting connections
postgresql_1  | INFO  ==> Changing password of postgres
postgresql_1  | INFO  ==> Configuring replication parameters
postgresql_1  | INFO  ==> Configuring fsync
postgresql_1  | INFO  ==> Loading custom scripts...
postgresql_1  | INFO  ==> Enabling remote connections
postgresql_1  | INFO  ==> Stopping PostgreSQL...
postgresql_1  | INFO  ==> ** PostgreSQL setup finished! **
postgresql_1  |
postgresql_1  | INFO  ==> ** Starting PostgreSQL **
postgresql_1  | 2019-06-17 20:42:56.977 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql_1  | 2019-06-17 20:42:56.978 GMT [1] LOG:  listening on IPv6 address "::", port 5432
postgresql_1  | 2019-06-17 20:42:56.982 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql_1  | 2019-06-17 20:42:57.011 GMT [189] LOG:  database system was shut down at 2019-06-17 20:42:55 GMT
postgresql_1  | 2019-06-17 20:42:57.030 GMT [1] LOG:  database system is ready to accept connections
discourse_1   | nami    INFO  Initializing postgresql-client
discourse_1   | postgre INFO  Trying to connect to PostgreSQL server
postgresql_1  | 2019-06-17 20:42:58.397 GMT [196] LOG:  incomplete startup packet
discourse_1   | postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgresql_1  | 2019-06-17 20:42:58.418 GMT [197] LOG:  incomplete startup packet
discourse_1   | postgre INFO  PostgreSQL server listening and working at postgresql:5432
postgresql_1  | 2019-06-17 20:42:58.605 GMT [199] FATAL:  role "bn_discourse" does not exist
discourse_1   | postgre ERROR [canConnect] Connection with 'bn_discourse' user is unsuccessful
discourse_1   | postgre INFO  ==> Creating database bitnami_application...
discourse_1   | postgre INFO  ==> Granting access to bn_discourse to the database bitnami_application...
discourse_1   | nami    INFO  postgresql-client successfully initialized
sidekiq_1     | nami    INFO  Initializing discourse-sidekiq
discourse_1   | nami    INFO  Initializing discourse
discourse_1   | discour INFO  Patching Discourse...
discourse_1   | postgre INFO  Trying to connect to PostgreSQL server
postgresql_1  | 2019-06-17 20:43:07.111 GMT [207] LOG:  incomplete startup packet
discourse_1   | postgre INFO  Found PostgreSQL server listening at postgresql:5432
discourse_1   | postgre INFO  PostgreSQL server listening and working at postgresql:5432
discourse_1   | discour INFO  Preparing Discourse environment...
discourse_1   | discour INFO  Configuring the Discourse database files...
discourse_1   | discour INFO  Configuring Redis...
discourse_1   | discour INFO  Setting up SMTP in Discourse...
discourse_1   | discour INFO  Configuring Discourse database...
discourse_1   | discour INFO  Enabling PostgreSQL plugins for Discourse...
discourse_1   | discour INFO  Migrating database...
sidekiq_1     | postgre INFO  Trying to connect to PostgreSQL server
postgresql_1  | 2019-06-17 20:44:02.030 GMT [214] LOG:  incomplete startup packet
sidekiq_1     | postgre INFO  Found PostgreSQL server listening at postgresql:5432
sidekiq_1     | postgre INFO  PostgreSQL server listening and working at postgresql:5432
sidekiq_1     | discour INFO  Configuring the Discourse database files...
sidekiq_1     | discour INFO  Configuring Redis...
sidekiq_1     | discour INFO  Setting up SMTP in Sidekiq...
sidekiq_1     | discour INFO  Waiting for Discourse service to be ready...
discourse_1   | discour INFO  Creating the Discourse admin user...
discourse_1   | discour INFO  Configuring your Discourse installation...
discourse_1   | discour INFO
discourse_1   | discour INFO  ########################################################################
discourse_1   | discour INFO   Installation parameters for discourse:
discourse_1   | discour INFO     Username: user
discourse_1   | discour INFO     Password: **********
discourse_1   | discour INFO   (Passwords are not shown for security reasons)
discourse_1   | discour INFO  ########################################################################
discourse_1   | discour INFO
discourse_1   | nami    INFO  discourse successfully initialized
discourse_1   | Starting discourse...
sidekiq_1     | nami    INFO  discourse-sidekiq successfully initialized
sidekiq_1     | Starting discourse-sidekiq...
discourse_1   | Migrating to CopyLoginRequiredWelcomeMessage (20190125103246)
discourse_1   | Migrating to AddTextSizeSeqToUserOption (20190125153345)
discourse_1   | Migrating to AddIndexOnUserIdToSingleSignOnRecords (20190130013015)
discourse_1   | Creating scope :open. Overwriting existing method Poll.open.
discourse_1   | Creating scope :open. Overwriting existing method Poll.open.
discourse_1   | [ N 2019-06-17 20:50:51.8453 4053/T1 age/Wat/WatchdogMain.cpp:1366 ]: Starting Passenger watchdog...
discourse_1   | [ N 2019-06-17 20:50:51.8655 4056/T1 age/Cor/CoreMain.cpp:1339 ]: Starting Passenger core...
discourse_1   | [ N 2019-06-17 20:50:51.8657 4056/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
discourse_1   | [ N 2019-06-17 20:50:51.8772 4056/T1 age/Cor/CoreMain.cpp:1014 ]: Passenger core online, PID 4056
discourse_1   | [ N 2019-06-17 20:50:54.8454 4056/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
sidekiq_1     | # Logfile created on 2019-06-17 20:50:59 +0000 by logger.rb/61378
discourse_1   | Creating scope :open. Overwriting existing method Poll.open.
sidekiq_1     | 2019-06-17T20:51:09.900Z 104 TID-gobusnjbo INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :namespace=>"sidekiq", :id=>"Sidekiq-server-PID-104", :url=>nil}
discourse_1   | Started HEAD "/" for 127.0.0.1 at 2019-06-17 20:51:13 +0000
discourse_1   | Processing by ListController#latest as HTML
discourse_1   |   Rendering list/list.erb within layouts/application
discourse_1   |   Rendered list/list.erb within layouts/application (52.8ms)
discourse_1   |   Rendered layouts/_head.html.erb (139.8ms)
discourse_1   |   Rendered common/_discourse_stylesheet.html.erb (21.3ms)
discourse_1   |   Rendered application/_header.html.erb (1.2ms)
discourse_1   | Completed 200 OK in 2132ms (Views: 797.8ms | ActiveRecord: 260.5ms)
```

Which is the platform you are using? Did you modify the docker-compose.yml file so we can reproduce?

**Comment by Fruchtgummi** [comment]
I use Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-50-generic x86_64) and docker-compose version 1.24.0, build 0aa5906

**Comment by Fruchtgummi** [comment]
Okay, this one helped https://github.com/docker/docker-credential-helpers/issues/102#issuecomment-388974092

**Comment by Fruchtgummi** [comment]
jet have a new problem 

`


Creating discourse_discourse_1  ... error

ERROR: for discourse_discourse_1  Cannot start service discourse: driver failed programming external connectivity on endpoint discourse_discourse_1 (ddbc30186fdd7304763c7c61e5a08a171df5a6bed1d9d40352f8485b8676209a): Bind for 0.0.0.0:80 failed: port is already allocated

ERROR: for discourse  Cannot start service discourse: driver failed programming external connectivity on endpoint discourse_discourse_1 (ddbc30186fdd7304763c7c61e5a08a171df5a6bed1d9d40352f8485b8676209a): Bind for 0.0.0.0:80 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

`

**Comment by javsalgar** [comment]
It seems that you already have a container listening on port 80. Could you check it by executing `docker ps`?
