### ISSUE TITLE
Failed to start: unknown attribute 'email_private_messages' for UserOption

### ISSUE THREAD

**Issue by dhaavi** [bitnami/bitnami-docker-discourse#97]
Discourse fails to start after last upgrade to `bitnami/discourse latest 706bf917ab3b`. Issue may also have been introduced in the days prior and not immediately detected.

**Setup**

`bitnami/discourse` is connected to `postgres:10` and `redis:4`

**Log Output**

```
Welcome to the Bitnami discourse container,
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse,
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues,

WARN  ==> A persisted configuration file 'discourse.conf' was found inside '/bitnami/discourse/conf'.  This feature is not supported anymore. Please mount the configuration file at '/opt/bitnami/discourse/conf' instead.,
WARN  ==> A persisted configuration file 'database.yml' was found inside '/bitnami/discourse/conf'.  This feature is not supported anymore. Please mount the configuration file at '/opt/bitnami/discourse/conf' instead.,
nami    INFO  Initializing postgresql-client,
nami    INFO  postgresql-client successfully initialized,
nami    INFO  Initializing discourse,
discour INFO  Patching Discourse...,
postgre INFO  Trying to connect to PostgreSQL server,
postgre INFO  Found PostgreSQL server listening at postgresql:5432,
postgre INFO  PostgreSQL server listening and working at postgresql:5432,
discour INFO  Preparing Discourse environment...,
discour INFO  Configuring the Discourse database files...,
discour INFO  Configuring Redis...,
discour INFO  Setting up SMTP in Discourse...,
discour INFO  Migrating database...,
Error executing 'postInstallation': rake aborted!,
ActiveModel::UnknownAttributeError: unknown attribute 'email_private_messages' for UserOption.,
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:46:in `eval',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute_assignment.rb:43:in `each',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute_assignment.rb:43:in `_assign_attributes',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/attribute_assignment.rb:23:in `_assign_attributes',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute_assignment.rb:35:in `assign_attributes',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/persistence.rb:440:in `block in update!',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/persistence.rb:439:in `update!',
(eval):52:in `block (2 levels) in run_file',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:46:in `eval',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:46:in `block (2 levels) in run_file',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:58:in `block in open',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:57:in `open',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:57:in `open',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:36:in `block in run_file',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:35:in `run_file',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:26:in `block in run',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:25:in `each',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu/runner.rb:25:in `run',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/seed-fu-2.3.9/lib/seed-fu.rb:29:in `seed',
/opt/bitnami/discourse/lib/tasks/db.rake:53:in `block in <top (required)>',
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>',
/opt/bitnami/ruby/bin/bundle:23:in `load',
/opt/bitnami/ruby/bin/bundle:23:in `<main>',
Tasks: TOP => db:migrate,
(See full trace by running task with --trace),
```

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

Slightly redacted.

```
Containers: 32
 Running: 22
 Paused: 0
 Stopped: 10
Images: 49
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: XXX
 Is Manager: true
 ClusterID: XXX
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: XXX
 Manager Addresses:
  XXX
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-54-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.28GiB
Name: XXX
ID: XXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by alemorcuq** [comment]
Hi, @dhaavi.

Can you give me some steps in order to reproduce the issue?

Regards,
Alejandro

**Comment by dhaavi** [comment]
Well, I don't really know how to reproduce as this happened during an automated upgrade of `bitnami/discourse`.

Is there a way to reset the installation without losing data?
Maybe reset the plugins? Could they be an issue here?

**Comment by alemorcuq** [comment]
Hi, @dhaavi.

I've been able to reproduce and identify your issue. It's being caused by the `discord-narrative-bot` plugin, which is being persisted and thus is not up to date. I've created an internal task to investigate it further and figure out a fix for it.

In the meantime, you can try this workaround to recover your installation:
curl -L https://github.com/discourse/discourse/archive/v2.3.1.tar.gz > discourse.tar.gz
1. Get into a bash shell in the `discourse` container.
2. Download the 2.3.1 release of Discourse:
```console
$ cd /tmp && curl -L https://github.com/discourse/discourse/archive/v2.3.1.tar.gz > discourse.tar.gz
```
2. Remove the core plugins by doing:
```console
$ rm -r /bitnami/discourse/plugins/{discourse-details,discourse-local-dates,discourse-narrative-bot,discourse-nginx-performance-report,discourse-presence,lazyYT,poll}
```
3. Copy the newer plugins to the `plugins` directory:
```console
$ cp -r /tmp/discourse-2.3.1/plugins/{discourse-details,discourse-local-dates,discourse-narrative-bot,discourse-nginx-performance-report,discourse-presence,lazyYT,poll} /bitnami/discourse/plugins/
```
4. Change the owner of each of the plugins to `1001:1001`:
```console
chown -R 1001:1001 /bitnami/discourse/plugins/{discourse-details,discourse-local-dates,discourse-narrative-bot,discourse-nginx-performance-report,discourse-presence,lazyYT,poll}
```
5. Bring down the container and launch it normally.

Hope this helps.

Regards,
Alejandro

**Comment by dhaavi** [comment]
Hi @alemorcuq,

Thank you very much for investigating further, we appreciate this.

Your workaround worked flawlessly! Just had to fix a couple permissions after playing around with backups before ;)

This may be important for you: the only plugin that was in the plugin directory was `discourse-cronos`.

**Comment by alemorcuq** [comment]
I'm glad it worked, @dhaavi. Don't hesitate to contact us again with any issue you may have.

**Comment by mebibou** [comment]
I'm experiencing the same issue:
- I was using discource on one VM using also bitnami/discourse:latest
- I needed to migrate to a new VM, so I backup up postgres and redis containers
- copying the exact same `docker-compose.yml` file and backups and env variables, I started the containers on the new VM
- now I am getting this error:
```
Error executing 'postInstallation': rake aborted!
discourse     | ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "email_private_messages" of relation "user_options" does not exist
discourse     | LINE 1: UPDATE "user_options" SET "email_private_messages" = FALSE, ...
```

In attempt to match exactly the same images on both VM, I inspected `docker image inspect bitnami/discourse:latest` on the original VM and saw the version was created on `2018-12-04T08:50:59.845909891Z`, which seems to match `2.1.3-r18`. So instead of using `latest` tag on new VM, I used `2.1.3-r18` to match old VM.

=> The error is still there. Does that mean it's impossible to do a simple backup and restore?

**Comment by alemorcuq** [comment]
Hi, @mebibou.

Have you tried the solution explained in https://github.com/bitnami/bitnami-docker-discourse/issues/97#issuecomment-510964374? It's caused because of a plugin that it's getting persisted and isn't getting updated. Removing and replacing it should fix this.

Regards,
Alejandro

**Comment by mmacfadden** [comment]
I am having this same issue.  We are using the docker images in kubernetes, so I don't think the workaround would work for us. Trying to upgrade to 2.3.3. At the moment the site is down. Any help would be much appreciated.

**Comment by alemorcuq** [comment]
Hi, @mmacfadden.

You can override the container command in Kubernetes. You can use `sleep infinity` as the command, connect manually to the container and do the steps in the workaround, and then remove the custom command so the container executes its own command.

Will that work for you? Let me know how it goes.

Regards,
Alejandro

**Comment by mmacfadden** [comment]
@alemorcuq We think alike. I tried that last night, and yes I as able to get this to work!

**Comment by alemorcuq** [comment]
I'm glad it worked, @mmacfadden. Let us know if you find any other problems.

**Comment by marcosbc** [comment]
The issue is similar to https://github.com/bitnami/bitnami-docker-discourse/issues/161#issuecomment-804110918. For now the proposed solution involves adding an Upgrade Troubleshooting section in the README with the use of `DISCOURSE_SKIP_INSTALL`.
